name: 'aws-s3-website'
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1 

    - name: Remove existing content from S3 bucket
      run: |
        aws s3 rm s3://website.war24ever.id/ --recursive

    - name: Sync new content to S3 bucket
      run: |
        aws s3 cp --recursive . s3://website.war24ever.id/